### ISSUE TITLE
grants and proposals permissions

### ISSUE THREAD

**Issue by aturling** [EPSCoR/ERCore#10]
Hi, I recently noticed that under Accomplishments -> Grants and Proposals, that page is restricted to admin and admin staff. Is that because it includes proposals rejected, which is sensitive information? Have other jurisdictions left these settings in place, or has anyone adjusted the permissions to allow others (e.g. faculty) to view the proposals?

**Comment by khuffman** [comment]
We kept the existing permissions for Grants and Proposals,
Me think they make sense because of the sensitive nature of the whole 
grant and proposal issue, e.g. rejections, or proposals under review 
should not be visible to anyone else except the admin and admin staff.

Kia

**Comment by iserna** [comment]
Hi Amy, Our install only allows Admin and Admin Staff to view the Accomplishments page (which includes Grants and Proposals)  I am not sure what other jurisdictions are doing.  Though, with your new related content view by components will allow everyone in that component to see Grants and Proposals for their components. At least it should.  

By the way, we disable the ability for Faculty, Admin, and any other role to see the EPSCoR link in the black Admin nav bar.
- Isis

**Comment by aturling** [comment]
The version of the team content view that I sent out a while back would allow all team members to view team proposals, no matter what the status is. I just changed the permissions to make it admin/admin staff only for now so that it matches the summary page. I'm not sure what the permissions should be there - should team members see all of their team's proposals, just the accepted proposals, or none?

**Comment by iserna** [comment]
I would duplicate what the summary page has but recommend that you ask your admin just to be sure.
