### ISSUE TITLE
Table C

### ISSUE THREAD

**Issue by aturling** [EPSCoR/ERCore#13]
Is anyone currently working on fixing the issue with Table C where collaborators from participating institutions aren’t being counted? Is there any timeline for when this will be fixed? Our project admins are working on the NSF report now, and it’d be really helpful to have it working before the deadline on May 1.

I looked at the code on pages/collaborations.inc but it would take a while to understand what's going on. Is there any chance it's as simple as commenting out this line?

$query->condition("participating.{$participating}_value", '0');//must be an external institution

especially since there's already this line below that seems to filter out participants:

$query->condition("status.{$collab_user_status}_value", 'Collaborator');//Person must be marked as a collaborator

**Comment by iserna** [comment]
Chris and I talked with Mary Jo last Thursday about this.  Chris had a fix, that I tested on my local install but it did not work for me.  

We have not talked or worked on it since.  

I can try what you recommend to see if it works.

Also, we can have a quick call to talk about how collaborations work so you can understand it better.

-Isis

**Comment by iserna** [comment]
@aturling I just tested your recommendation on local test site.

Commenting out the following line does count all the collaborators.
$query->condition("participating.{$participating}_value", '0');//must be an external institution

Though, it also counts the institution too and it should not.  
- Isis

**Comment by aturling** [comment]
So just to check, are these the correct rules for Table C?
1. If A and B are Collaborators from a Non-Participating University, "Number of Institutions" is incremented by 1 and "Number of Collaborators" is incremented by 2
2. If A and B are Collaborators (not EPSCoR participants) from a Participating University, "Number of Institutions" is unchanged and "Number of Collaborators" is incremented by 2
3. If A and B are Participants from a Participating University, all counts are unchanged.

Then it would be possible to have a row like this:

Number of Institutions: 0
Number of Collaborators: (some nonzero number)

if all of the collaborators (non-participants) happen to be from a participating institution for that institution category and type.

**Comment by iserna** [comment]
@aturling yes, you are correct.  Do you have a possible solution for this?
- Isis

**Comment by cjallen-epscor** [comment]
Resolved by @aturling at https://github.com/EPSCoR/ERCore-3.1/commit/861cb4b6ba7a678e4e9f5ddbd89edb14e9e398b0
