### ISSUE TITLE
Encryption 'sub-module'

### ISSUE THREAD

**Issue by cjallen-epscor** [EPSCoR/ERCore#17]
So, at "modules/er_encryption" is it safe to say that we can delete this directory/sub-project of ERCore? Initially, the collaborators at Hawaii requested this feature. The rest of the collaboration did not seem to enthused about it. 
We don't use this at NM and don't know of any one else using it as development of this sub module came to a halt when Hawaii discontinued with the collaboration.

Thoughts?

**Comment by khuffman** [comment]
In RI we are not using it. So we would not miss it if it got deleted.
Kia

**Comment by iserna** [comment]
Yes, I think it may worth deleting.  Though, we will need to ask everyone on the Admin side specifically Hawaii since they were the jurisdiction requiring it.  Let's leave it as is for now.
