### ISSUE TITLE
Rules Monthly Notification - Proposal/Grant

### ISSUE THREAD

**Issue by cjallen-epscor** [EPSCoR/ERCore#21]
I have created a rule at http://dev-ercore.nmepscor.net 
- EVENT - Proposals/Grants (after saving/updating a Proposal/Grant)
- CONDITION - Proposal Status: NOT awarded/denied
- ACTION
- (1)Send initial email 
  "You have entered proposal at [node:url].
  Please provide update to the proposal/grant (Awarded, Denied, etc) at your earliest convenience. "
- (2)In addition (automatically attach reminders 1-6 month out)
  Email: "Follow up e-mail for [account:uid] and proposal [node:title] created at [node:url]
  If this award has been updated (Awarded/Denied) please login and provide an update at [node:edit-url]."

This reminder sends automatically one month after Proposal/Grant created with only "Submitted" selected. The only caveat to this is that once the proposal is created the notification is triggered - hence if proposal is "Awarded" 3 months after it's created  - the user will continue to receive 4-6 month alerts as it's already triggered by the rule set.

I was thinking of maybe adding in the email notifications 
- "If you have already completed your proposal/grant update disregard this email"  or
- "Please notify 'support@ercore.com' to remove you from this notification.

Not sure what the best route would be. Please send suggestions for this workflow.

Check it out -http://dev-ercore.nmepscor.net/admin/config/workflow/rules/reaction/manage/rules_proposal_reminder

**Comment by cjallen-epscor** [comment]
As this rule involves rule scheduler (time based dependent on cron); 'rules components' needs to be used.
I have already included the code in the module locally so that these rules get bundled in ercore.

**Comment by iserna** [comment]
We found that this notification broke our Proposal & Grant content type.  It generated, in some cases, the  error (attached) for the author.  At first we thought it was the character length of the title but it was the rule + scheduler that broke it.

![error___epscor_reporting](https://cloud.githubusercontent.com/assets/8584825/14330374/90f90832-fbfd-11e5-9b71-3cccdf309547.png)

Closing this issue.
