### ISSUE TITLE
export for New Investigators shows incorrect number and names of people

### ISSUE THREAD

**Issue by khuffman** [EPSCoR/ERCore#22]
Description: on our site when we go to EPSCoR->Admin Views->New Investigators we get a list of people, that looks correct. But then when we chose the export to XLS (or CSV) we get a very short list that contains names of people who aren't new investigators.

How to fix: In the 
admin/structure/views/view/er_flagged_for_new_investigator/edit/views_data_export_1
display:
- under filter criteria section add: Participations Date, and Most Senior Project role (just like the admin/structure/views/view/er_flagged_for_new_investigator/edit/page )
- remove the limit Page, to show All Items.

When going through this, I found out something else that doesn't make sense to us:
the query date is asking for Participation start date range "now" to -365 day. 
So for example if you request this view on March 10,2015 it will return all faculty who joined 365 days before March 10,2015. But both Sally and I think it should be instead from the reporting year start (for us is Aug 1).  What do you think?

**Comment by iserna** [comment]
Export is fixed.   Closing this issue.
