### ISSUE TITLE
Code Cleanup and Module Renaming

### ISSUE THREAD

**Issue by Renrut5** [EPSCoR/ERCore#24]
So I had an idea as a way to work on updating the code in ER Core to change the reference from 'er' to 'ercore.'

I created a Google spreadsheet where we can list all the file names in the module that would need to be updated. A person can go through and update a file and commit it to a new branch or version of ER Core (perhaps v. 4.0-dev).

Then, once the file is updated, we should have another person check the committed file. This way we have multiple eyes on each file and a way to organize who did what and what has already been done.

The spreadsheet has three columns, the file name, who updated it, and who checked it. The link is below, and you'll be able to edit the file with that link. 

https://docs.google.com/spreadsheets/d/1bZiZqKNBddlB1Vh35FexzS84DsDpqcpVuv2k_2wHAsA/edit?usp=sharing

I haven't yet added any file names, but I can start if others think this is a worthwhile idea.

**Comment by iserna** [comment]
@Nerdacious this sounds like a good starting point and a good way to document and track changes.  Thank you for setting up the spreadsheet.  

I would like to get some feedback from the rest of the team (tech and admin) before moving forward though.  If we don't hear anything back with the week, we can bring it talk about it in the next meeting.

Thanks!

**Comment by iserna** [comment]
I am closing this for now since this will be something that will get folded into the Official Release proposal.
