### ISSUE TITLE
verify ethnicity value in outputs.inc

### ISSUE THREAD

**Issue by khuffman** [EPSCoR/ERCore#27]
@cjallen-epscor  back in July 2014 you committed an outputs.inc file
https://github.com/EPSCoR/ERCore-3.1/commit/d1a2198afd427eeededa7d399c54cc230cb4b90f
One of the changes you made was you switched  0 to 1 for the ethnicity (0=Hispanic-latino ,1=not Hispanic-latino). 
But when I apply the latest outputs.inc 
https://github.com/EPSCoR/ERCore-3.1/blob/3.1-dev/pages/outputs.inc
to our testsite,  suddenly in Table E all people who have set their ethnicity to "not hispanic-latino" are counted as "underrepresented minority". Then if I go and switch 1 back to 0 ( line 197 ) then all shows correct.
Can you please verify that this 0 to 1 switch gets the correct number of  "underrepresented minority" on your site. Thanks.

**Comment by cjallen-epscor** [comment]
@khuffman -- very strange. I could have swore I resolved this with the correct Hispanic values at */admin/config/people/accounts/fields/field_er_ethnicity

Anyway, all should be good now as I made the corrections at: 
Commit: https://github.com/EPSCoR/ERCore-3.1/commit/bebda46f26da4ad9a17e030fab30b7b29c932d52

**Comment by cjallen-epscor** [comment]
Sorry - error on my part. The correct commit is at : https://github.com/EPSCoR/ERCore-3.1/commit/8b8ad0bee6acc0c0997a706255885928226e3946
