### ISSUE TITLE
"No Default Date" on user profile date fields

### ISSUE THREAD

**Issue by cjallen-epscor** [EPSCoR/ERCore#3]
per @khuffman, she noticed that in the user profile the following fields have a default date set to "now".

RCR dates
participation date
hired date
Data repository submission

This should be set to "no default value".

Solution shall be pushed in ERCore 3.1

**Comment by cjallen-epscor** [comment]
@iserna - on your fresh install locally, can you confirm the user profile date default values for the following: (either 'no default value' or 'now')

RCR dates
participation date
hired date
Data repository submission

**Comment by iserna** [comment]
@cjallen-epscor on my local install, from March 2015, for fields mentioned (RCR, participation, hired date, and Data repository submission) all default values are 'no default value'.
