### ISSUE TITLE
Position Type Taxonomy?

### ISSUE THREAD

**Issue by tschet** [EPSCoR/ERCore#36]
What does the position type taxonomy do? Is it used? I see references to it in the code. There are half a dozen MySQL queries to it, but I can't see that its used anywhere. There doesn't appear to be any active fields that reference the taxonomy.

**Comment by iserna** [comment]
@tschet I just reviewed our live site and we are not referencing this taxonomy term anywhere.  This may be a left over from the initial development of the module.  

@khuffman, @aturling, @cjallen-epscor can you all confirm if you are or not using the Position Type taxonomy term.

Thanks.

**Comment by tschet** [comment]
I would appreciate that, thanks.

**Comment by khuffman** [comment]
I do not recall to ever have used Position Type taxonomy in anything I 
modified for our jurisdiction, so I'm pretty sure we are not using it 
here in RI.

Kia

**Comment by cjallen-epscor** [comment]
@tschet - I can confirm that we are not using that taxonomy. I'm pretty sure it was leftover from an original proposed User Profile system that the team strayed away from.

**Comment by aturling** [comment]
We are also not using position type; the term list is empty.

**Comment by tschet** [comment]
North Dakota doesn't use it either. I did add another taxonomy so they could track both categories (components) and projects (new taxonomy) separately. Thanks for the quick replies.

**Comment by cjallen-epscor** [comment]
I propose we remove this taxonomy from core since we are not using it.

**Comment by cjallen-epscor** [comment]
This taxonomy has been removed from the 3.x branch - https://github.com/EPSCoR/ERCore-3.1/commit/5e9d67f76423eaf967b758e56577a20f3943750d
