### ISSUE TITLE
Dependencies: Undeclared and Unnecessary  

### ISSUE THREAD

**Issue by tschet** [EPSCoR/ERCore#37]
The ERCore module has two undeclared dependencies and two unnecessary ones.
List and number are undeclared but necessary.
Rules_admin and views_ui are listed as dependencies but are not required. Both Rules and Views can run without their UI's being turned on. They can be safely shut off on production sites when not being used.

**Comment by cjallen-epscor** [comment]
@tschet - I cut a new ERCore Branch - 7.x-3.2-dev and committed this change there. 
https://github.com/EPSCoR/ERCore-3.1/commit/faccf6f80f0f96158658b61f9db5f8536d26c86a
