### ISSUE TITLE
upload of participants to Research.gov issue

### ISSUE THREAD

**Issue by khuffman** [EPSCoR/ERCore#39]
We have been trying to upload an er-core generated participants xls file to Research.gov but have not had much luck. 
During the Sept.30 er-core Admin meeting I brought up this issue, it seems that a lot of jurisdictions have the same problem, so it was decided that we are going to contact someone in HelpDesk at Research.gov to have a phone meeting with a few of us.

**Comment by iserna** [comment]
@khuffman I spoke with Mary Jo and she was successful at uploading the NM EPSCoR participant list for our last reporting deadline in May, 2015.  She said all she did was fall back on an older version of excel, .xls instead of .xlsx.  There's an option, in research.gov, to pick which version you want to upload.  She also mentioned that there's a column of data that research.gov asks for but we do not gather this info from ERCore, she could not remember what this data.  I requested that she please send me the spreadsheet she uploaded so we can analyze it and use it to trouble shoot the issue.  

Have you tried uploading an older version of excel?

**Comment by khuffman** [comment]
@iserna  I only have access to the Research.gov Demo site (instructions are below for those who want to try it). So far I have found a couple of issue with our er-core generated participant list (ESPCoR->Participants) that might be causing the problems. Here below is my findings so far about this topic:

Problem1:
From the Demo site I download a xls participant file(not the xlsx), and I can see in that file that the category of the participants doesn't match our er-core categories. For example here is screenshot of their categories: (same in the xls file from them)
![research_gov_demo_categories](https://cloud.githubusercontent.com/assets/8309906/10227847/b3dafc1a-683d-11e5-9d41-0623c3b5a983.jpeg)

In our er-core generated xls participant list under "Most Senor Project Role" column for example a faculty is listed as "Faculty participant (or equivalent)" but in Research.gov it is listed as "Faculty", the same issue with "Technical support staff" in er-core, because this category doesn't exist in Research.gov category list.

Problem2:
The category column in Research.gov xls file is an array/drop-down menu showing the available categories. Ours  er-core column is just a single entry text field. Could this be causing the problem?

Problem 3: 
Research.gov requires the "International travel" and  "Foreign Collaborator" columns (mandatory). Our er-core participant xls file doesn't have that info, but we have been adding this manually, so this is not a huge issue.

Anyhow, even after modifying our xls to match the Reseach.gov Demo site, I tried to upload it to the Demo site, but I never see the people added to their table. Maybe this is a restriction with the Demo site? Can HelpDesk tell us if this is the case?
But Sally says she has same problem on the real Reseach.gov.

------How to get to Reseach.gov Demo site--------
Go to http://www.research.gov/ under "Awards & Reporting" , click on 2nd link "Example Project Reports (Demo site)" , then chose PI Demo Site.
Now you will see a list of awards, scroll down to e.g.report number 1000001 , then click the "Create/Edit"
Next, click on "Participants/Organizations" tab.Then click  "Add/Edit multiple participants" button, just above the table, on the right, to ge to the page where you can download the xls file (and later upload it)

**Comment by iserna** [comment]
I will draft a brief process of what I did to prep the people spreadsheet.  For the NM Annual Report, yr3, I successfully uploaded this file twice.  It has also been recommended that we work to populate this file but we are not sure yet if it would be helpful considering you always have to edit the Nearest Person Month Worked, the International Collaboration, and the Traveled to Foreign Country.

**Comment by iserna** [comment]
Participant Sample file from research.gov
[participantsFile-1000001.zip](https://github.com/EPSCoR/ERCore-3.1/files/206766/participantsFile-1000001.zip)

**Comment by iserna** [comment]
It has been determined that this question/issue is different for each individual tasked with uploading the participants spreadsheet to research.gov.  NM and other jurisdictions have been successful while others have not.
