### ISSUE TITLE
EPSCoR PI/co-PI not shown in teaser for Proposal or Grant

### ISSUE THREAD

**Issue by khuffman** [EPSCoR/ERCore#4]
When someone adds a new content of type "Proposal or Grant", in the teaser that is shown on the Home Page, the EPSCoR PI/co-PI's entry is not shown. The non-EPSCoR PI/co-PI is shown.
I fixed this problem by going to Structure->Content Types->Proposal or Grant->Manage Display.
The from the upper right hand corner select the "teaser" button, and then drag the EPSCoR fields from hidden to the area that you want it to be. Push Save. Done.

**Comment by cjallen-epscor** [comment]
Nice. Easy fix too. I can apply this into 3.1-dev

**Comment by khuffman** [comment]
I have only looked at teasers for Proposals and Publications but I 
believe a few other content types suffer from similar issue.
In Content Type: Publication's teaser EPSCoR author and/or non-EPSCoR 
author has been omitted from the teaser.

Kia

**Comment by cjallen-epscor** [comment]
Teaser displays updated and committed below: 
Publication - https://github.com/EPSCoR/ERCore-3.0/commit/73b381955ccaa3121fbc57cafcef7f2d1e8e3368
Presentation - https://github.com/EPSCoR/ERCore-3.0/commit/7fc256f947caaeab994f0964304c0166b21c9856
Proposal/Grant - https://github.com/EPSCoR/ERCore-3.0/commit/e5e54df228105a4fc6abbf4aff383fddeb582a9b
Collaboration - https://github.com/EPSCoR/ERCore-3.0/commit/49d42c3da00a2a6b95d15d9eb78028d9dfcd06c6
