### ISSUE TITLE
User guide / Proposals and grants

### ISSUE THREAD

**Issue by tschet** [EPSCoR/ERCore#40]
The user guide seems to refer to Proposals and Grants pages as being a multi-step form that associates  "Participant Effort" with users. I don't see any sign of that configuration in a default installation. Was that removed or never finished?

**Comment by iserna** [comment]
@tschet are you referring to bullet #2 under Proposals and Grants?

**Comment by tschet** [comment]
Yes I am

**Comment by iserna** [comment]
The only place, I know of, where Participant Effort collected is in the User Profile in the EPSCoR Involvement section.  
I do not see any sign of it in the Proposals and Gants content type or in Template E where the P&Gs are populated.  
I will investigate a little more and let you know.  Though, it looks like the user guide just needs to be updated by taking out that bullet item.

Thanks

**Comment by cjallen-epscor** [comment]
@iserna - I have looked this up and found an archived Trello card created by Mike P. (Original ERCore developer at Hawaii). He states: 

> #### Proposal Effort nodes can be removed (again)
> 
> "I've confirmed with Kevin and Hanalei that this information is neither needed for Table A or for Research.gov, and can be removed.
> 
> Reason: Table A has been changed/simplified. The table only asks for "individual funded effort (in months)" for "EPSCoR RII", in other words it only asks for your effort in the epscor project, and not external grants. Similarly, R.gov wants to know your effort to the epscor project. This information can be attained through the user profile." (https://trello.com/c/yhi5vn6q)

@iserna @tschet 
We can update the User Guide to remove the 'multi-step' wording.

**Comment by cjallen-epscor** [comment]
The User Guide has been updated at https://github.com/EPSCoR/ERCore-3.1/commit/dabd011af483d92335b6635ee47c2953ebcdd905
