### ISSUE TITLE
Propose ERCore Rules be eliminated

### ISSUE THREAD

**Issue by cjallen-epscor** [EPSCoR/ERCore#47]
We don't use any of the rules bundled in ERCore here in NM - therefore I propose we remove the three rules bundled in ERCore:
- Rule: rules_er_receive_data_notifications_flagged  
- Rule: rules_er_send_data_collection_notifications  
- Rule: rules_er_receive_data_notifications_unflagged

This would eliminate one dependency (Rules). 

Thoughts?

**Comment by iserna** [comment]
Is anyone else using them?  If not, I would recommend taking them out.

**Comment by aturling** [comment]
We’re not using them either.

**Comment by cjallen-epscor** [comment]
Rules have been removed https://github.com/EPSCoR/ERCore-3.1/commit/574b8148a5910664ac3258b89afa9428c2ce7bd3
