### ISSUE TITLE
.directory file in views directory

### ISSUE THREAD

**Issue by tschet** [EPSCoR/ERCore#48]
In the 3.1.1 branch, there is a .directory file in the views directory. There way Views are handled in the ER module, ANY file in the views directory is assumed to be a View and is imported. This file causes PHP errors, at a minimum ,every time the cache is cleared.
Please delete it.

**Comment by cjallen-epscor** [comment]
@tschet - I have removed this file from the 3.1.1 branch https://github.com/EPSCoR/ERCore-3.1/commit/bfc0e935aeb722a46cb7bae035c6ff3f94b34b10
