### ISSUE TITLE
Latest commit of 3.1.1 is broken

### ISSUE THREAD

**Issue by tschet** [EPSCoR/ERCore#49]
I updated a development site which had an out of date version of ERCore (six months old?) installed. I found that in the newest ERCore module version, the er_user_reference_selection View was broken and un-editable. It appears to be missing some sort of required Views plugin. Thinking that I had some sort of upgrade problem, I deleted the database and reinstalled. That didn't work either.  The last commit to 3.1.1 break the module's ability to install. I didn't test the other two March 30th commits,  Just the newest one.

`UnexpectedValueException: DirectoryIterator::__construct(sites/all/modules/er/install/rules): failed to open dir: No such file or directory in DirectoryIterator->__construct() (line532 of/Users/username/Sites/devel1/sites/all/modules/er/includes/er.install.inc).`

I rolled my local development site back to the [February commit](https://github.com/EPSCoR/ERCore-3.1/commit/dc6b4c39eaa7a9c1837e751111ca62e096e18376) and the installation worked just fine. However, on that version the er_user_reference_selection View is still broken. It looks like a dependency is not identified as required, or a Views plugin that used to be in the module is no longer present or working.

**Comment by tschet** [comment]
The er_user_reference_selection View is dependent on the References module, which to my knowledge isn't used elsewhere in the module. There is not a dependency for it. I think that's the wrong View, it should use the Entity Reference View handler.

**Comment by aturling** [comment]
I got the same error just now when installing a fresh copy of ER Core to add my changes to the user dashboard module, and installing + enabling References seemed to fix it.

**Comment by aturling** [comment]
Actually, no I think it’s still not working. None of the default roles were entered, and going to this page:
/admin/config/epscor/status
I get the same error.

**Comment by cjallen-epscor** [comment]
@tschet @aturling - I receieved this same error on a local dev server. Due to the removal of rules from ERCore the module is looking for the folder 'rules'. I patched this with the last two commits at https://github.com/EPSCoR/ERCore-3.1/commits/3.1.1 
- Commit: https://github.com/EPSCoR/ERCore-3.1/commit/f356e290717601911fbc73d66379857d1fbd5f1e
- Commit:  https://github.com/EPSCoR/ERCore-3.1/commit/086b3f1c19b34b7613b8992e1466c9e40ecefeaf
