### ISSUE TITLE
Data Integrity Check

### ISSUE THREAD

**Issue by cjallen-epscor** [EPSCoR/ERCore#56]
I propose we add this to ERCore 3.2
Enabled here http://dev-ercore.nmepscor.net/admin/epscor/views/check

Thoughts?

**Comment by iserna** [comment]
@cjallen-epscor Yes, this should be included in 3.2.  The Admin team got a peek of this view at their meeting in DC and all agreed (who were there) that it is useful.

**Comment by cjallen-epscor** [comment]
View has been added to 3.2-dev branch - 
https://github.com/EPSCoR/ERCore-3.1/commit/8f19ea099783cea18b7553153350d1cd29439d78
