### ISSUE TITLE
in user's Demographic is N/A option shown?

### ISSUE THREAD

**Issue by khuffman** [EPSCoR/ERCore#64]
A question: in your jurisdiction's ERCore, when you go into a user's profile, in Edit form under the Demographic tab, is the N/A option shown for the various radio buttons? like here, for example see here: http://dev-ercore.nmepscor.net/user/13/edit
Or did you do something specific to hide the N/A option?

**Comment by khuffman** [comment]
I know in form_logic.inc there this this function, 
_remove_NA_option($form, &$form_state)
that gets called for various form items, but I wonder why this _remove_NA_option() function is not being used for the Demographic items? was there a reason for it?

**Comment by aturling** [comment]
I left "N/A" under Gender and Ethnicity as sort of a "prefer not to respond" option. I hid it for Disabilities (which already has "none" as an option) and Race (which already has a "prefer not to respond" option). I did this + other user profile customizations in a custom module to avoid changing the ER Core code.

**Comment by ercore** [comment]
In NM we left the N/A and I have no idea why they were left in.  Though, I did find this note about the N/A option on the old Trello Board, note is from @cjallen-epscor on 1/14/2014!

> Without setting the field to "required" the "N/A" option will appear. I did add the option of "Prefer not to respond".
> According to http://drupal.stackexchange.com/questions/38032/widget-type-radio-buttons-and-n-a
> "N/A is implemented that way, because otherwise users don't have any way to deselect a radio button, and for some (government) sites that's a requirement.
> To change it use: - a form_alter in a custom module
> - javascript inside your theme to hide the N/A option.
> - theme_options_none
>   I think showing the n/a field is not a problem. Ethnicity, disability, and other Demographic fields have this as well.

Kia, if you still have access to the trello board here's the direct link to the card, https://trello.com/c/AEcWrWFz

Thanks!
Isis

**Comment by khuffman** [comment]
@ercore thank you very much for finding this old Trello note. OK, now I understand better the reasoning behind why the N/A is by purpose not hidden for some fields(such as gender etc)  but is hidden by purpose for other fields (field_er_faculty_any_support). Thanks!

**Comment by cjallen-epscor** [comment]
@khuffman - yeah basically if a field is not marked as required (gender/race/etc) then by default Drupal adds a "N/A". As mentioned in my card from 2014 "N/A is implemented that way, because otherwise users don't have any way to deselect a radio button, and for some (government) sites that's a requirement."

Easy way would be to hide via states in form_logic.inc

**Comment by ercore** [comment]
@khuffman did you resolve this issue/question on your site?

**Comment by khuffman** [comment]
Yes, it is resolved, thanks.
