### ISSUE TITLE
Table A (salary-support.inc still contains typo)

### ISSUE THREAD

**Issue by khuffman** [EPSCoR/ERCore#65]
I'm working on Table A (= EPSCoR->Admin Views->NSF Table A -Salary Support). On our site Table A's html page shows names of faculty grouped by their institution and in the xls file we get an xls file with columns "Institution", "Department" and "Faculty Name (Last, First)" all filled in, but all the other columns are empty. I hope I can find a way of getting at least the efforts column filled in, the best scenario would be if I could get the total efforts from each "faculty group"(=faculty+students/postdoc)

@cjallenunm I wanted to see how the Table A looks on NewMexico test site, so I logged in there and noticed that Table A html is blank and the xls file's  columns "Institution", "Department" and "Faculty Name are all empty. I suspected that the typo/bug that I wrote to you (+ Isis, Amy see email from me Feb 27, 2015 subject:  fixed bug/typo in NSF Table A ) is still there, so I looked in the 7.x-3.2 code branch, and noticed that in er/pages/salary-support.inc the typo/bug are indeed there

Typo: in this line https://github.com/EPSCoR/ERCore/blob/7.x-3.2/pages/salary-support.inc#L38
Faculty participants (or equivalent) should be replaced with:
Faculty participant (or equivalent)
so no "s" after participant. This typo also exists in this file debug.inc see: https://github.com/EPSCoR/ERCore/blob/7.x-3.2/pages/debug.inc#L105

Bug: this line: https://github.com/EPSCoR/ERCore/blob/7.x-3.2/pages/salary-support.inc#L96
should be this:

```
$output .= "<h3>".l($name, 'user/'.$uid).$department."</h3>";
```

Anyway at least these two fixes will help table A a bit...long way left to get the efforts in etc.

**Comment by cjallen-epscor** [comment]
@khuffman - thanks for the small typo patches! I applied your changes in the 7.x-3.2 branch (https://github.com/EPSCoR/ERCore/commits/7.x-3.2) and applied those changes at http://dev-ercore.nmepscor.net/reporting/salary-support and now the people are populating. Thanks for working on this!

**Comment by ercore** [comment]
@khuffman I think it was late last year or earlier this year that you originally fixed and shared this typo.  I did apply it to our dev reporting site here in NM but either Mary Jo or Anne felt that we needed it.  From them, they stated that we do not collect all the relevant information to accurately populate this template.  Instead, they use other established systems to gather this information and then manually enter the data.  

This is not to say that other jurisdictions using the D7 ER Core do not want to populate this data with your fix.  With that, @aturling and @tschet please communicate this fix to your Admin Reporters.  They may very well find this fix useful.  If you do not fully understand the "fix" please see http://dev-ercore.nmepscor.net/reporting/salary-support as an example.  Feel free to use this example when explaining to your Admin Reports what it does and what it does not do.  

Kia, thank you for your continued support in fixing and building upon this template and for sharing your work!  We truly appreciate your time and effort in the consortium.

Thanks!
Isis
