### ISSUE TITLE
External collaborator node title can be too long

### ISSUE THREAD

**Issue by aturling** [EPSCoR/ERCore#67]
I just ran into this issue on our site: because the external collaborator node title is stored in the format "[name] from [department] @ [institution] on [collaboration name]" and one external collaborator had the combination of 1) a long name, 2) a long department name, and 3) the collaboration itself had a long title (163 chars), the overall title for the external collaborator node was too long to be stored in the database.

I reduced the character limit for collaboration titles which is probably enough to prevent this from happening again. Another option is to truncate this string to the character limit in includes/node_logic.inc (https://github.com/EPSCoR/ERCore/blob/7.x-3.2/includes/node_logic.inc#L285):

$node->title = "$name from $inst_with_dept on {$collab->title}";

Has anyone else experienced this?

**Comment by ercore** [comment]
@aturling we have not experienced this in NM.  I will ask if anyone else has during our meeting this afternoon. 
Thanks!

**Comment by ercore** [comment]
This has not been an issue for other jurisdictions but everyone agreed that this fix is relevant and will implement if and when needed.
