### ISSUE TITLE
Collaboration CT error - 

### ISSUE THREAD

**Issue by cjallen-epscor** [EPSCoR/ERCore#7]
When clicking on "Add a name to this collaboration" the User lookup populates all data with the exception of the referenced user's institution being checked.

@aturling @khuffman -- can you verify that this is the same for your installs?

**Comment by aturling** [comment]
I'm not seeing this on the test site. Just to verify - here are the steps I took to try to recreate this:
- create new collaboration
- add a collaborator to the collaboration
- lookup user and select "auto-fill fields below"
  When I do that, the user's institution is auto-selected (radio buttons). I tested it with one user from a "participating institution" and one from a "non-participating institution" and it worked both ways.

**Comment by cjallen-epscor** [comment]
@aturling - is this at http://dev-ercore.nmepscor.net ? 

I tried on Firefox, Chrome, and Safari and the user's institution is still not being selected....

**Comment by aturling** [comment]
Ok I see what you're talking about, I did get the error at dev-ercore. But it's not showing up on our live reporting site or my offline test site. I was looking through the modules to see what the differences are. I don't know if this affects anything, but here's what I see:

Dev-ercore
- Entity API version 7.x-1.5
- Entity tokens 7.x-1.5

MO reporting site/test site
- Entity API version 7.x-1.6
- Entity tokens 7.x-1.6

Some modules installed on Dev-Ercore that aren't installed on MO live/test sites:
CCK, Node Reference, References, User Reference

plus some other differences that wouldn't be relevant here (like the different versions of the Flag module)

**Comment by cjallen-epscor** [comment]
@aturling - I did investigate the modules and jQuery versions and nothing seemed to work.
This feature works correctly on our live NM install and that install has the same setup as yours. 

As a testing measure, this fails to fire the institution on my local turnkey testing site; which does have everything up to date. Very strange.

@khuffman - is your install having the same issue?

**Comment by khuffman** [comment]
I tested on my laptop's  er-core\* and I do not see this error. 
Everything works fine (after I type in the first few character of 
someone's name, then it shows me their full name, and then I click 
"Auto-fill fields below" and it fills in everything correctly including 
the Institution, I do not see any errors.)

I'm doing it as a user who has er's "Administrative Staff" role.
What user-role are you trying this as?

Also make sure that the Institution for the user you are adding is not 
"DRAFT" (go to EPSCoR->EPCoR Content->Institutions
In the list make sure the institution that the user belongs to is not 
set to DRAFT.)

I have these modules both my laptop/live site:
Entity API  7.x-1.6
Entity tokens   7.x-1.6
Entity Reference 7.x-1.1
Entity reference prepopulate    7.x-1.4

Kia
*which is almost a clone of our live site (I cloned it today so I 
haven't messed it up too much, only difference is I added Amy's new team 
view to my laptop this afternoon)

**Comment by cjallen-epscor** [comment]
Update:
Strange. When I was in the system today - I was getting the error:

## Strict warning: Only variables should be passed by reference in er_form_er_collaborators_node_form_alter() (line 121 of /var/www/dev-ercore.nmepscor.net/sites/all/modules/epscor_reporting_core/includes/form_logic.inc).

```
            $arraypopvalue = $u->field_er_inst_ref->raw();
        $form_state['input']['field_er_collab_inst_ref']['und'] = array_pop($arraypopvalue);
        // Earlier/original code    
            //$form_state['input']['field_er_collab_inst_ref']['und'] = array_pop($u->field_er_inst_ref->raw());    

    // This works but is invalid with newer PHP versions
            // 
    // New Version - that resolves the error:
    //
    // modified by Chris - cjallen@epscor.unm.edu
    $arraypopvalue = $u->field_er_inst_ref->raw();
    $form_state['input']['field_er_collab_inst_ref']['und'] = array_pop($arraypopvalue);
```

---

After performing those changes dev-ercorenmepscor.net now populates the institution for collaborations.

I will apply this patch into ERCore 3.1-dev

**Comment by cjallen-epscor** [comment]
Patch committed at https://github.com/EPSCoR/ERCore-3.0/commit/4148534952e26282b1b2ef36c4bc48087321e796
